### ISSUE TITLE
TODO lists

### ISSUE THREAD

**Issue by Big-Cake-jpg** [Big-Cake-jpg/Big-Cake-jpg#4]
- [ ] Rewrite README
- [ ] Add more details
- [ ] Add Platforms and Tools
- [ ] Add slogan
- [ ] Remove undesired content
